export enum APIEndPoints {
  ExpensesManagement = '/api/ExpensesManagement',
  Data = '/api/Data',
  Prediction = '/api/Prediction',
  Authentication = '/api/controller',
  Intractions = '/api/controller',
  FamilyNotes = '/api/FamilyNotes',
  FinancialPlanner = '/api/FinancePlanner',
  DigitalAssistant = '/api/DigitalAssistant',
  WeatherForecast = '/api/WeatherForecast',
  ContactMessage = '/api/ContactMessage',
  Contact = '/api/Contact',
  MedicalContact = '/api/MedicalContact',
  Location = '/api/Location',
  Calander = '/api/Calendar',
  Emergency = '/api/Emergency',
  GoogleGeoCode = 'https://maps.googleapis.com/maps/api/geocode/json',
  Manage = '/api/Manage',
  Subscription = '/api/Subscription',
  Executor = '/api/Executor',
  PasswordManager = '/api/PasswordManager',
  EmergencyNumber = '/api/EmergencyNumbers',
  Professiona = '/api/FCProfessional',
}
